CREATE TABLE "company"
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT company_pkey PRIMARY KEY,
    name                   VARCHAR(256) NOT NULL,
    ogrn                   VARCHAR(13) NOT NULL,
    activity_description   VARCHAR(256) NOT NULL,
    chief_id               BIGINT
)